### PR TITLE
Checkin process

### PR DESCRIPTION
**Pull request by gdaunton**
This adds the check-in process. It starts by checking location and trying to check-in the bike that way. If the endpoint does not take the location coords, the option to scan a check-in qr code is given.

@Xcelled Do you think this flow is OK? Not too sure about having the qr code scan be the backup. It means that sometimes returning a bike is going to be two requests.

### Bike is checked out:
screenshot_20171123-132616

### Click Return button, start of process:
screenshot_20171124-002736

### Return failed because of invalid location:
screenshot_20171124-002739

cc @TJohnW

### CODE REVIEW

**Comment by Xcelled** [comment]
You can tell if the backend will accept coords by looking at the DROP_ANYWHERE property of `/status/`. You could cache this on app startup and then use that to determine if you should try coords or force a scan.

**Comment by gdaunton** [comment]
Right, I'm saying that we should try to match the location to a bike rack when they check in. That way they don't have to go around looking for the are code to return their bike.

**Comment by gdaunton** [comment]
Updated the success screens for check-in and check-out.

### Check-in
screenshot_20171124-123242

### Check-out
screenshot_20171124-123308

**Comment by Xcelled** [comment]
Oh I see what you mean. I'll have to change the backend slightly to support that... You don't need to do multiple requests to figure this out, though. Bike racks have a `checkInArea` field which is the geometry the backend would check anyway. If you check it clientside, you don't need to make an extra request. 

The format of the field is Well Known Text. You can convert this to geoJson with something like [this](https://github.com/mapbox/wellknown) and then dump that into [turfjs](http://turfjs.org/) to check if the phone is currently inside the checkin area.

**Comment by Xcelled** [comment]
Actually, I can have the backend dump out geoJson directly to save you that step.

**Comment by gdaunton** [comment]
Awesome, if I do it client side I can also account for the accuracy of the location data since I get a lat long with a radius of accuracy.

**Comment by Xcelled** [comment]
geoJson is now enabled. And since you're doing the check client-side, just send the ID of the rack that you find instead of the coords of the user (if drop anywhere is not enabled).

Also make sure you only find exactly _one_ rack. If their location is imprecise and covers multiple racks, it should fail too!

**Pull request merged**
